const ROUTER = {
  LOGIN: "/dang-nhap",
  OVERVIEW: "/overview",
  USER: "/nguoi-dung",
  ACCOUNT: "/tai-khoan",
  ACCESSORIES: "/phu-tung",
  LIST_ACCESSORIES: "/danh-muc-phu-tung",
  CAR: "/xe",
  LIST_CAR: "/danh-muc-xe",
  PRODUCT: "/san-pham",
  ADD_PRODUCT: "/them-san-pham",
  LIST_PRODUCT: "/danh-muc-san-pham",
  ORDER: "/don-hang",
  REQUEST_PURCHASES: "/yeu-cau-mua-hang",
  INSURRANCE: "/bao-hiem",
  UPDATE_INSURRANCE: "/sua-bao-hiem",
  ADD_INSURRANCE: "/them-bao-hiem",
  LIST_INSURRANCE: "/danh-muc-bao-hiem",
  INSURRANCE_ORDER: "/don-mua-bao-hiem",
  REQUEST_ADVICE: "/yeu-cau-tu-van",
  LOAN_CAPITAL_PACK: "/goi-vay-von",
  ADD_LOAN_CAPITAL_PACK: "/them-goi-vay-von",
  REQUEST_LOAN_PACK: "/yeu-cau-vay-von",
  PROFILE: "/ho-so",
  ORDER_NEED_TRANSPORT: "/don-hang-can-chuyen",
  VEHICLE_POSTING: "/tin-dang-cua-xe",
  VEHICLE_POSTING_DETAIL: "/chi-tiet-tin-dang",
  PROJECT: "/du-an",
  SERVICE: "/dich-vu",
  SUPPORT_CHAT: "/ho-tro-chat",
  REQUEST_SERVICE: "/yeu-cau-dich-vu",
  OLD_CAR_POSTING: "/tin-dang-xe-cu",
  NEWS: "/tin-tuc",
  ADD_NEWS: "/them-tin-tuc",
  UPDATE_NEWS: "/sua-tin-tuc",
  CONFIG: "/cau-hinh",
  REQUEST_SERVICE_DETAIL: "/chi-tiet-yeu-cau-dich-vu",
};

// xin ý kiến nên tách hay không và tách ntn
// Anh Tuấn + Tùng

export { ROUTER };
